### ISSUE TITLE
Неправильное отображение окон при добавлении сайта

### ISSUE THREAD

**Issue by Nekit10** [KoniDevTeam/SiteMonster#2]
При добавлении нового сайта, окно редактирования его настроек неактивно и находится за окном со списком сайтов (если последний не передвигать).

**Comment by ITGrusha** [comment]
На винде такого нет

**Comment by Nekit10** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Баги](https://trello.com/c/bfJqACUg/42-%D0%B1%D0%B0%D0%B3%D0%B8)

**Comment by Nekit10** [comment]
Теперь на винде такое есть

**Comment by Nekit10** [comment]
Нахрен убрал отображение этого окна, все проблемы убрались
Коляхейтер не злись, это было вынужденное решение
